//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotepadGps.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotepadGps.Resource.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя чтобы заданная дата была меньше текущей даты.
        /// </summary>
        internal static string AlertDate {
            get {
                return ResourceManager.GetString("AlertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match.
        /// </summary>
        internal static string ConfirmPasswordAlert {
            get {
                return ResourceManager.GetString("ConfirmPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждаете ли вы удаление?.
        /// </summary>
        internal static string DeleteAccept {
            get {
                return ResourceManager.GetString("DeleteAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поля Title, Longitude, Latitude и Description.
        /// </summary>
        internal static string FieldsAlert {
            get {
                return ResourceManager.GetString("FieldsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your action.
        /// </summary>
        internal static string ImgSourceChoose {
            get {
                return ResourceManager.GetString("ImgSourceChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный почтовый адрес.
        /// </summary>
        internal static string MailAlert {
            get {
                return ResourceManager.GetString("MailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already taken.
        /// </summary>
        internal static string MailConflict {
            get {
                return ResourceManager.GetString("MailConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password!.
        /// </summary>
        internal static string MailPasswordAlert {
            get {
                return ResourceManager.GetString("MailPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно быть не менее 4 и не более 16 символов. Имя не должно начинаться с цифер.
        /// </summary>
        internal static string NameAlert {
            get {
                return ResourceManager.GetString("NameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 8 и не более 16 символов. Пароль должен содержать минимум одну заглавную букву, одну строчную букву и одну цифру.
        /// </summary>
        internal static string PasswordAlert {
            get {
                return ResourceManager.GetString("PasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email.
        /// </summary>
        internal static string SignInMailAlert {
            get {
                return ResourceManager.GetString("SignInMailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        internal static string SignInPasswordAlert {
            get {
                return ResourceManager.GetString("SignInPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string SignUpMailAlert {
            get {
                return ResourceManager.GetString("SignUpMailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string SignUpNameAlert {
            get {
                return ResourceManager.GetString("SignUpNameAlert", resourceCulture);
            }
        }
    }
}
